- name: Deploy App
  hosts: local_vm
  become: true

  tasks:
    - name: add java
      apt_repository:
        repo: ppa:openjdk-r/ppa
        state: present

    - name: install dependencies
      apt:
        update_cache: yes
        name: 
          - openjdk-17-jdk
          - git
        state: present

    - name: remove pre-existing repo
      file:
        path: /opt/spring-petclinic
        state: absent

    - name: clone repo
      ansible.builtin.git:
        repo: https://github.com/dorryspears/spring-petclinic-group-project.git
        dest: /opt/spring-petclinic
        version: main

    - name: build app
      shell: ./mvnw package
      args:
        chdir: /opt/spring-petclinic

    - name: stop existing application
      shell: pkill java || true
      ignore_errors: yes
      
    - name: start application
      shell: nohup java -jar target/*.jar &
      args:
        chdir: /opt/spring-petclinic
        
    - name: wait for app to start
      wait_for:
        port: 8080
        timeout: 60
