version: "3.8"

services:
  petclinic:
    build: .
    container_name: petclinic
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - postgres
    restart: always

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  postgres:
    image: postgres:15
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  mysql-data:
  postgres-data:
