FROM ghcr.io/zaproxy/zaproxy:stable

# Set working directory
WORKDIR /zap

# Create a script to run ZAP and handle the report
COPY --chmod=755 run-zap.sh /zap/

# Set the entry point to our script
ENTRYPOINT ["/zap/run-zap.sh"]
