services:
  jenkins:
    image: my-jenkins
    container_name: jenkins-test
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - network

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana-test
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - network

  prometheus:
    image: prom/prometheus
    container_name: prometheus-test
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
    networks:
      - network

  sonarqube:
    image: sonarqube:10.6-community
    container_name: sonarqube-test
    ports:
      - "9000:9000"
    networks:
      - network

volumes:
  grafana-storage:
    external: true
  jenkins_home:
    external: true
  prometheus-data:
    external: true

networks:
  network:
    external: false